### ISSUE TITLE
save and open map problem

### ISSUE THREAD

**Issue by theextremeandy** [micrology/prsm#131]
First of all many compliments to professor Nigel Gilbert for his precious work. It is difficult to find such interesting projects here.

my problem is that when I save the map on local disk and reload it, through the toolbar functions, the nodes appear smaller without and the edges without the modified settings, as if it were at a basic level.

since loading the examples loads the maps correctly, I guess there is a problem in the saving phase.

has anyone solved this problem?
thanks!
andy

![beforesave](https://github.com/user-attachments/assets/ca1a5859-d2b2-41e4-b615-e3a54a47aa75)
![afterload](https://github.com/user-attachments/assets/55c5a362-5c50-4cf3-8fa8-2d8c10b0b225)

**Comment by micrology** [comment]
Hi,

Could you send me a link to the map (i.e. what is ‘XXX-XXX-XXX-XXX’ in https://prsm.uk/prsm.html?room=XXX-XXX-XXX-XXX) and/or the saved file?

Thank you,

Nigel



From: extremeandy ***@***.***>
Date: Tuesday, 17 September 2024 at 17:10
To: micrology/prsm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [micrology/prsm] save and open map problem (Issue #131)

First of all many compliments to professor Nigel Gilbert for his precious work. It is difficult to find such interesting projects here.

my problem is that when I save the map on local disk and reload it, through the toolbar functions, the nodes appear smaller without and the edges without the modified settings, as if it were at a basic level.

since loading the examples loads the maps correctly, I guess there is a problem in the saving phase.

has anyone solved this problem?
thanks!
andy

beforesave.PNG (view on web)<https://github.com/user-attachments/assets/ca1a5859-d2b2-41e4-b615-e3a54a47aa75>
afterload.PNG (view on web)<https://github.com/user-attachments/assets/55c5a362-5c50-4cf3-8fa8-2d8c10b0b225>

**Comment by theextremeandy** [comment]
dear professor
thanks a lot for your work and your prompt reply this is the
code VDB-DSD-PNE-BBU
it should still be active because I could not compile the web socket. I'm
not that expert :-(
thanks for any help

**Comment by micrology** [comment]
Hi,

That map:

https://prsm.uk/prsm.html?romm=VDB-DSD-PNE-BBU

is empty.  Maybe you miss-typed the code?

Would you also send me a copy of the .prsm file you saved?


Nigel



From: extremeandy ***@***.***>
Date: Tuesday, 17 September 2024 at 17:30
To: micrology/prsm ***@***.***>
Cc: Gilbert, Nigel Prof (Sociology) ***@***.***>, Comment ***@***.***>
Subject: Re: [micrology/prsm] save and open map problem (Issue #131)
dear professor
thanks a lot for your work and your prompt reply this is the
code VDB-DSD-PNE-BBU
it should still be active because I could not compile the web socket. I'm
not that expert :-(
thanks for any help

**Comment by micrology** [comment]
I didn’t find any attachment.

Would you try your model with the public version at https://prsm.uk/prsm.html and see whether your problem remains?

Nigel




From: extremeandy ***@***.***>
Date: Wednesday, 18 September 2024 at 08:51
To: micrology/prsm ***@***.***>
Cc: Gilbert, Nigel Prof (Sociology) ***@***.***>, Comment ***@***.***>
Subject: Re: [micrology/prsm] save and open map problem (Issue #131)
attached is the saved map
I remembered that the build returned an error and I had to downgrade the
version of "sharp" to "^0.31.1"
;-)

**Comment by theextremeandy** [comment]
Hi Gilbert
I hope this attachment works!
andrea

**Comment by micrology** [comment]
Still no attachment.

Please also do as I suggested:

 > Would you try your model with the public version at
 > https://prsm.uk/prsm.html and see whether your problem remains?

Thank you.

**Comment by theextremeandy** [comment]
sorry
all attachments don't work from gmail
but the prsm file can't be attached here either

I'll try from here now
this video is from public version:
https://github.com/user-attachments/assets/e9032f7e-745f-4c91-8bfb-6c17687c502c

**Comment by micrology** [comment]
Thanks for the video.  It illustrates the issue clearly.  I’ll take a look and update you.

Nigel




From: extremeandy ***@***.***>
Date: Wednesday, 18 September 2024 at 13:10
To: micrology/prsm ***@***.***>
Cc: Gilbert, Nigel Prof (Sociology) ***@***.***>, Comment ***@***.***>
Subject: Re: [micrology/prsm] save and open map problem (Issue #131)

sorry
all attachments don't work from gmail
but the prsm file can't be attached here either

I'll try from here now
this video is from public version:
https://github.com/user-attachments/assets/e9032f7e-745f-4c91-8bfb-6c17687c502c

**Comment by theextremeandy** [comment]
thank you very much Nigel
i will wait as long as it takes
andrea

**Comment by micrology** [comment]
Sorry it has taken so long (the bug was difficult to find), but I believe it is now fixed.  However, you'll need to refresh your map, as follows:
1. Open the map file in the current version (now updated to version 2.3.4)
2.  You will see the nodes are still without margins (i.e. smaller than you expected). Click on the `Share` button in the top Nav bar.
3. Click on `Copy to clipboard`
4. Paste the copied web link into your browser's address bar and hit return.
5. Click the `Leave` button in the 'Leave site' dialog (may be worded differently depending on your browser) 
6.  The map will reappear, but the nodes will have regained their margins, i.e. got bigger again. 
7. Save the map as a .prsm file.
8. When you open this newly saved file, the nodes will stay larger, as they should.

**Comment by theextremeandy** [comment]
thanks Prof Nigel,
it seems to work
I point out that if I change the type of link for example to "triangle" when saving and reloading the change is lost
we are very close though
andrea

**Comment by micrology** [comment]
Thank you for pointing this out.  It is corrected in the latest version.

Nigel



Nigel Gilbert
Lead developer, PRSM<https://prsm.uk/>
***@***.***

From: extremeandy ***@***.***>
Date: Thursday, 10 October 2024 at 18:08
To: micrology/prsm ***@***.***>
Cc: Gilbert, Nigel Prof (Sociology) ***@***.***>, State change ***@***.***>
Subject: Re: [micrology/prsm] save and open map problem (Issue #131)

thanks Prof Nigel,
it seems to work
I point out that if I change the type of link for example to "triangle" when saving and reloading the change is lost
we are very close though
andrea

**Comment by theextremeandy** [comment]
Hi Nigel,
Yes! also the change of type of link work fine now
Thank you
B/R
andrea
